INSERT INTO public.city (id, name) VALUES (1, 'Prague'), (2, 'Berlin'), (3, 'Vienna');

INSERT INTO public.museum (id, name, description, city_id, address, ticket_info, photo) VALUES
  (1, 'National museum', 'The National Museum is the largest museum in the Czech Republic. As the central state museum with collecting, scientific, educational and methodological functions it seeks to enhance the sense of national identity and awareness of being part of the whole framework of European and world community and culture.', 1, 'Václavské nám. 68', '100 - 200 CZK', 'https://myohotelwenceslas.blob.core.windows.net/imagehandler/Media/ContentItems/1089_01089/m_max__o/museum.jpeg'),
  (2, 'National Technical Museum', 'The National Technical Museum in Prague is the largest institution dedicated to preserving information and artifacts related to the history of technology in the Czech Republic. The museum was founded in 1908 and has been in its current location (adjacent to Letná Park) since 1941.', 1, 'Kostelní 1320/42', '70-150 CZK', 'https://www.pensioncampprague.com/images/national-technical-museum.jpg'),
  (3, 'Kunsthistorisches Museum (Art History Museum)', 'The Kunsthistorisches Museum (Art History Museum) was built in 1891 near the Imperial Palace to house the extensive collections of the imperial family. With its vast array of eminent works and the largest Bruegel collection in the world, it is considered one of the most eminent museums in the world.', 2, 'Maria-Theresien-Platz', '15-30 EUR', 'https://aws-tiqets-cdn.imgix.net/images/content/1871e79477e74468b73080a23361a2b5.jpg?auto=format&fit=crop&ixlib=python-3.2.1&q=25&s=91b63fadc783728afad6385ab3bb3910&w=375&h=250&dpr=2.625'),
  (4, 'Gallery Albertina', 'The Albertina not only has the largest and most valuable graphical collections in the world, with works such as Dürer’s “Hare” and Klimt''s studies of women. Its latest exhibition collection presents masterpieces of the Modern, spanning Monet to Picasso and Baselitz. As the largest Habsburg residential palace, the Albertina dominates the southern tip of the Imperial Palace on one of the last remaining fortress walls in Vienna.', 2, 'Albertinaplatz 1', '15-25 EUR', 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Albertina1.JPG'),
  (5, 'Belvedere', 'The Belvedere is not only a magnificent Baroque palace but also houses one of Austria''s most valuable art collections – with key works by Gustav Klimt, Egon Schiele and Oskar Kokoschka.', 2, 'Prinz-Eugen-Straße 27,', '7-20 EUR', 'https://media-cdn.tripadvisor.com/media/photo-s/11/e9/db/10/magnificient.jpg'),
  (6, 'Leopold Museum', 'Hundreds of masterworks of Austrian modern art collected by the passionate art lover Dr. Rudolf Leopold are shown in the Leopold Museum at MuseumsQuartier near the Imperial Palace.', 2, 'Museumsplatz 1', '10-20 EUR', 'https://www.leopoldmuseum.org/media/image/c950x576/3924.jpg'),
  (7, 'mumok - Museum of Modern Art', 'The mumok - Museum of Modern Art Ludwig foundation Vienna in the MuseumsQuartier focuses its attention on the art of the 20th and 21st centuries. Works by Andy Warhol, Claes Oldenburg, Pablo Picasso, Yoko Ono, Günter Brus and Gerhard Richter invite visitors to engage with contemporary art.', 2, 'Museumsplatz 1', '12-25 EUR', 'https://i.pinimg.com/originals/3d/df/06/3ddf064e6442ca3b5d6a76ed6fe03d5a.jpg');
