INSERT INTO public.city (id, name) VALUES (1, 'Prague'), (2, 'Berlin'), (3, 'Vienna');

INSERT INTO public.museum (id, name, description, city_id, address, ticket_info, photo, latitude, longitude) VALUES
  (1, 'National museum', 'The National Museum is the largest museum in the Czech Republic. As the central state museum with collecting, scientific, educational and methodological functions it seeks to enhance the sense of national identity and awareness of being part of the whole framework of European and world community and culture.', 1, 'Václavské nám. 68', '100 - 200 CZK', 'https://myohotelwenceslas.blob.core.windows.net/imagehandler/Media/ContentItems/1089_01089/m_max__o/museum.jpeg', 50.078995, 14.430910),
  (2, 'National Technical Museum', 'The National Technical Museum in Prague is the largest institution dedicated to preserving information and artifacts related to the history of technology in the Czech Republic. The museum was founded in 1908 and has been in its current location (adjacent to Letná Park) since 1941.', 1, 'Kostelní 1320/42', '70-150 CZK', 'https://www.pensioncampprague.com/images/national-technical-museum.jpg', 50.097099, 14.425207),
  (3, 'Kunsthistorisches Museum (Art History Museum)', 'The Kunsthistorisches Museum (Art History Museum) was built in 1891 near the Imperial Palace to house the extensive collections of the imperial family. With its vast array of eminent works and the largest Bruegel collection in the world, it is considered one of the most eminent museums in the world.', 3, 'Maria-Theresien-Platz', '15-30 EUR', 'https://aws-tiqets-cdn.imgix.net/images/content/1871e79477e74468b73080a23361a2b5.jpg?auto=format&fit=crop&ixlib=python-3.2.1&q=25&s=91b63fadc783728afad6385ab3bb3910&w=375&h=250&dpr=2.625', 48.203885, 16.361752),
  (4, 'Gallery Albertina', 'The Albertina not only has the largest and most valuable graphical collections in the world, with works such as Dürer’s “Hare” and Klimt''s studies of women. Its latest exhibition collection presents masterpieces of the Modern, spanning Monet to Picasso and Baselitz. As the largest Habsburg residential palace, the Albertina dominates the southern tip of the Imperial Palace on one of the last remaining fortress walls in Vienna.', 3, 'Albertinaplatz 1', '15-25 EUR', 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Albertina1.JPG', 48.204717, 16.368187),
  (5, 'Belvedere', 'The Belvedere is not only a magnificent Baroque palace but also houses one of Austria''s most valuable art collections – with key works by Gustav Klimt, Egon Schiele and Oskar Kokoschka.', 3, 'Prinz-Eugen-Straße 27,', '7-20 EUR', 'https://media-cdn.tripadvisor.com/media/photo-s/11/e9/db/10/magnificient.jpg', 48.191456, 16.381040),
  (6, 'Leopold Museum', 'Hundreds of masterworks of Austrian modern art collected by the passionate art lover Dr. Rudolf Leopold are shown in the Leopold Museum at MuseumsQuartier near the Imperial Palace.', 3, 'Museumsplatz 1', '10-20 EUR', 'https://www.leopoldmuseum.org/media/image/c950x576/3924.jpg', 48.202675, 16.359184),
  (7, 'mumok - Museum of Modern Art', 'The mumok - Museum of Modern Art Ludwig foundation Vienna in the MuseumsQuartier focuses its attention on the art of the 20th and 21st centuries. Works by Andy Warhol, Claes Oldenburg, Pablo Picasso, Yoko Ono, Günter Brus and Gerhard Richter invite visitors to engage with contemporary art.', 3, 'Museumsplatz 1', '12-25 EUR', 'https://i.pinimg.com/originals/3d/df/06/3ddf064e6442ca3b5d6a76ed6fe03d5a.jpg', 48.203837, 16.357920),
  (8, 'Rudolfinum Gallery', 'The Rudolfinum Gallery is a spacious and attractive art gallery situated in the multi-purpose Rudolfinum cultural complex, which houses a gorgeous concert hall and a grand turn of the last century café. J. Schulz, who also designed the National Theater in Prague, which is a beautiful example of Historicist architecture in central Europe, designed this neo Renaissance building.', 1, 'Alšovo nábřeží 12', '0 - 200 CZK', 'https://www.prague-stay.com/images/full_image/1920x1200/prague%20rudolfinum%20exterior%201-resize~rudolfinum-gallery-concert-hall-entrance.jpg', 50.09021771326617, 14.416211894781304),
  (9, 'Troja Chateau - City Gallery Prague', 'The romantic Troja Chateau is home to the City Gallery Prague’s permanent exhibition and is located by a lovely bend in the Vltava River, surrounded by lovely gardens and an old vineyard. This wonderful chateau or villa was designed by Jean Baptiste Mathey upon the request of the glorious Sternberg family after Wenzel Adalbert von Sternberg embarked on his essential Grand Tour and returned to Bohemia with visions of Roman residential splendor in his mind (the chateau is inspired by the spacious 16th and 17th century villas Sternberg witnessed outside of Rome in the Frascati area).', 1, 'U Trojskeho Zamku 4/1', '150-250 CZK', 'https://www.prague-stay.com/images/full_image/1920x1200/prague%20troja%20chateau%20prague%20city%20gallery-resize~troja-chateau-city-gallery-pond.png', 50.11510417543283, 14.410922121468609),
  (10, 'Kampa Museum', 'An eccentric contemporary collection located on the left riverbank of the Vltava, housed in the old Sova Mill, named after Vaclav Sova, the original owner in the 15th century. It should be noted that this museum is worth a visit especially for the building that has been magnificently renovated after centuries of fires, floods, and damage. On a clear day in Prague one should head to Kampa Museum on Kampa Island.', 1, 'U Sovových mlýnů 2', '100-200 CZK', 'https://www.prague-stay.com/images/lifestyle_article_carousel/570x340/prague-kampa-exterior1-fit~kampa-island-and-the-museum-prague-museums-and-galleries.jpg', 50.084030882179334, 14.408357594177096),
  (11, 'The Franz Kafka Museum', 'Franz Kafka is undeniably one of Prague’s most famous sons. Born to a German speaking family in Prague (then part of Austria-Hungry), Kafka is famous as one of the top writers of the 20th century. Paving the way for artists and authors with his influence in Existentialism and Modernism, Kafka is represented widely in the city of Prague.', 1, 'Cihelná 2b', '100-200 CZK', 'https://www.prague-stay.com/images/lifestyle_article_carousel/570x340/prague%20franz%20kafka%20museum%20exterior-fit~franz-kafka-museum-complex-exterior.png', 50.08784616580876, 14.40981975003056);
